# Generated by Django 4.2.5 on 2023-10-19 12:44

import core.enums.invite_enum
import core.enums.request_enum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companymodel')),
                ('status', models.CharField(choices=[('accept', core.enums.request_enum.RequestEnum['ACCEPT']), ('decline', core.enums.request_enum.RequestEnum['DECLINE']), ('pending', core.enums.request_enum.RequestEnum['PENDING']), ('cancel', core.enums.request_enum.RequestEnum['CANCEL'])], default=None, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'request',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InviteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companymodel')),
                ('status', models.CharField(choices=[('approve', core.enums.invite_enum.InviteEnum['APPROVE']), ('rejected', core.enums.invite_enum.InviteEnum['REJECTED']), ('pending', core.enums.invite_enum.InviteEnum['PENDING']), ('cancel', core.enums.invite_enum.InviteEnum['CANCEL'])], default=None, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invite',
                'ordering': ('-created_at',),
            },
        ),
    ]
