# Generated by Django 4.2.5 on 2023-10-17 09:32

import core.enums.invitation_enum
import core.enums.user_enum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companymodel')),
                ('role', models.CharField(choices=[('owner', core.enums.user_enum.UserEnum['OWNER']), ('candidate', core.enums.user_enum.UserEnum['CANDIDATE']), ('employee', core.enums.user_enum.UserEnum['EMPLOYEE']), ('member', core.enums.user_enum.UserEnum['MEMBER'])], max_length=255)),
                ('invitation_status', models.CharField(choices=[('accepted', core.enums.invitation_enum.InvitationEnum['ACCEPTED']), ('rejected', core.enums.invitation_enum.InvitationEnum['REJECTED']), ('pending', core.enums.invitation_enum.InvitationEnum['PENDING'])], default=None, max_length=10)),
                ('request_status', models.CharField(choices=[('accepted', core.enums.invitation_enum.InvitationEnum['ACCEPTED']), ('rejected', core.enums.invitation_enum.InvitationEnum['REJECTED']), ('pending', core.enums.invitation_enum.InvitationEnum['PENDING'])], default=None, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee',
                'ordering': ('-created_at',),
            },
        ),
    ]
