# Generated by Django 4.2.5 on 2023-10-23 14:07

import core.enums.request_enum
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='status',
            field=models.CharField(choices=[('approved', core.enums.request_enum.RequestEnum['APPROVED']),
                                            ('rejected', core.enums.request_enum.RequestEnum['REJECTED']),
                                            ('pending', core.enums.request_enum.RequestEnum['PENDING']),
                                            ('canceled', core.enums.request_enum.RequestEnum['CANCELED'])],
                                   default=None, max_length=10, null=True),
        ),
    ]
