# Generated by Django 4.2.5 on 2023-10-17 09:55

import core.enums.invitation_enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='invitation_status',
            field=models.CharField(choices=[('accepted', core.enums.invitation_enum.InvitationEnum['ACCEPTED']), ('rejected', core.enums.invitation_enum.InvitationEnum['REJECTED']), ('pending', core.enums.invitation_enum.InvitationEnum['PENDING'])], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='request_status',
            field=models.CharField(choices=[('accepted', core.enums.invitation_enum.InvitationEnum['ACCEPTED']), ('rejected', core.enums.invitation_enum.InvitationEnum['REJECTED']), ('pending', core.enums.invitation_enum.InvitationEnum['PENDING'])], default=None, max_length=10, null=True),
        ),
    ]
