# Generated by Django 4.2.5 on 2023-10-30 15:54

import core.enums.invite_enum
import core.enums.request_enum
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invitations', '0002_alter_requestmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitemodel',
            name='status',
            field=models.CharField(choices=[('accepted', core.enums.invite_enum.InviteStatusEnum['ACCEPTED']),
                                            ('declined', core.enums.invite_enum.InviteStatusEnum['DECLINED']),
                                            ('pending', core.enums.invite_enum.InviteStatusEnum['PENDING']),
                                            ('revoked', core.enums.invite_enum.InviteStatusEnum['REVOKED'])],
                                   default='pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='status',
            field=models.CharField(choices=[('approved', core.enums.request_enum.RequestStatusEnum['APPROVED']),
                                            ('rejected', core.enums.request_enum.RequestStatusEnum['REJECTED']),
                                            ('pending', core.enums.request_enum.RequestStatusEnum['PENDING']),
                                            ('canceled', core.enums.request_enum.RequestStatusEnum['CANCELED'])],
                                   default='pending', max_length=10, null=True),
        ),
    ]
