version: '3.7'
networks:
  meduzzen:
    name: meduzzen
services:
  backend:
    container_name: meduzzen_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - meduzzen
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/drf_app
    restart: on-failure

  redis:
    image: "redis:7-alpine"
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server
    volumes:
      - ./cache:/data
    restart: on-failure
    networks:
      - meduzzen
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: "postgres:15-alpine"
    env_file:
      - .env
    networks:
      - meduzzen
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    restart: on-failure
volumes:
  postgres_data:
  cache: