# Generated by Django 4.2.5 on 2023-10-19 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='members',
            field=models.ManyToManyField(through='employee.EmployeeModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
