# Generated by Django 4.2.5 on 2023-10-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymodel',
            old_name='status',
            new_name='visible',
        ),
    ]
