# Generated by Django 4.2.5 on 2023-10-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_name_profilemodel_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ('-created_at',)},
        ),
    ]
