# Generated by Django 4.2.5 on 2023-10-19 12:44

import core.enums.user_enum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitations', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companymodel')),
                ('role', models.CharField(choices=[('owner', core.enums.user_enum.UserEnum['OWNER']), ('candidate', core.enums.user_enum.UserEnum['CANDIDATE']), ('member', core.enums.user_enum.UserEnum['MEMBER'])], max_length=255, null=True)),
                ('invite_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invitations.invitemodel')),
                ('request_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invitations.requestmodel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee',
                'ordering': ('-created_at',),
            },
        ),
    ]
