# Generated by Django 4.2.5 on 2023-10-31 07:56

import core.enums.user_enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='role',
            field=models.CharField(choices=[('owner', core.enums.user_enum.UserEnum['OWNER']), ('candidate', core.enums.user_enum.UserEnum['CANDIDATE']), ('member', core.enums.user_enum.UserEnum['MEMBER']), ('admin', core.enums.user_enum.UserEnum['ADMIN'])], max_length=255, null=True),
        ),
    ]
